## MIT License

## Copyright (c) 2018 Gustav von Zitzewitz

## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:

## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.

## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.

fps_interval: 5             # Interval [s] to print fps of the last interval in console
allow_memory_growth: True   # limits memory allocation to the actual needs
initial_model: "models/bw-ve-jd"          # determine the initial loaded model
trt_precision_mode: "FP32"
trt_is_dynamic_op: False
trt_minimum_segment_size: 50

# prediction configuration

pred_thresh: 0.0        # threshold for the inference
pred_classes: 5         # number of classes in the model
pred_csv_path: " "      # path of the csv file that list image to predict
pred_image_path: " "    # path of the image directory to predict
pred_dataset_name: " "  # name of the created dataset
pred_project_name: " "  # name of the created project
pred_api_key: " "       # api key for labelbox
pred_model: " "         # model name to use (in the models directory)
pred_classes_filter: [] # classes name to examine
pred_begin: 0           # the index of the csv to begin the prediction
pred_end: -1            # the index of the csv to end the prediction (-1 continue to the end)
