item {
  id: 1
  name: 'dice4'
}
item {
  id: 2
  name: 'path'
}
item {
  id: 3
  name: 'cashingreen'
}
item {
  id: 4
  name: 'dice2'
}
item {
  id: 5
  name: 'gate'
}
item {
  id: 6
  name: 'dice6'
}
item {
  id: 7
  name: 'dice5'
}
item {
  id: 8
  name: 'cashinred'
}
item {
  id: 9
  name: 'dice1'
}
item {
  id: 10
  name: 'roulette'
}

