name: Docker Image CI - Develop

on:
  push:
    branches: [ develop ]

jobs:
  proc_detection:
    name: Build proc_detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push proc_detection
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64, linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:develop
          cache-to: type=inline
          tags: |
            ghcr.io/${{ github.repository }}:develop